import {
  FaHeart,
  FaBloodSugar,
  FaBrain,
  FaBone,
  FaStethoscope,
  FaLungs,
  FaVenus,
  FaMars,
  FaAllergies,
  FaRegSmile,
} from 'react-icons/fa';

export const categories = [
  {
    categoryName: 'BabyCare',
  },
  {
    categoryName: 'Glucometer and TestStrips',
  },
  {
    categoryName: 'Health Devices',
  },
  {
    categoryName: 'Healthy Supplements',
  },
  {
    categoryName: 'Medicine',
  },
  {
    categoryName: 'PersonalCare',
  },
  {
    categoryName: 'Protein Powders and Drinks',
  },
  {
    categoryName: 'Sexual Wellness',
  },
  {
    categoryName: 'Tablets',
  },
  {
    categoryName: 'WomenCare',
  },
];


export const medicalProducts = [
  {
    productImage: 'image1.jpg',
    productTitle: 'Pain Relief Tablets',
    actualPrice: 15.99,
    discountPrice: 12.99,
    discountPercentage: 20,
  },
  {
    productImage: 'image2.jpg',
    productTitle: 'Cough Syrup',
    actualPrice: 9.99,
    discountPrice: 7.49,
    discountPercentage: 25,
  },
  {
    productImage: 'image3.jpg',
    productTitle: 'First Aid Kit',
    actualPrice: 29.99,
    discountPrice: 24.99,
    discountPercentage: 16.67,
  },
  {
    productImage: 'image4.jpg',
    productTitle: 'Antibiotic Ointment',
    actualPrice: 8.49,
    discountPrice: 6.99,
    discountPercentage: 17.65,
  },
  {
    productImage: 'image5.jpg',
    productTitle: 'Allergy Relief Tablets',
    actualPrice: 12.99,
    discountPrice: 10.99,
    discountPercentage: 15.38,
  },
  {
    productImage: 'image6.jpg',
    productTitle: 'Digital Thermometer',
    actualPrice: 19.99,
    discountPrice: 16.49,
    discountPercentage: 17.51,
  },
  {
    productImage: 'image7.jpg',
    productTitle: 'Eye Drops',
    actualPrice: 6.99,
    discountPrice: 5.49,
    discountPercentage: 21.45,
  },
  {
    productImage: 'image8.jpg',
    productTitle: 'Bandages Pack',
    actualPrice: 7.99,
    discountPrice: 6.49,
    discountPercentage: 18.77,
  },
  {
    productImage: 'image9.jpg',
    productTitle: 'Vitamin C Tablets',
    actualPrice: 11.99,
    discountPrice: 9.99,
    discountPercentage: 16.68,
  },
  {
    productImage: 'image10.jpg',
    productTitle: 'Hand Sanitizer Gel',
    actualPrice: 5.99,
    discountPrice: 4.49,
    discountPercentage: 25.04,
  },
  {
    productImage: 'image11.jpg',
    productTitle: 'Nasal Spray',
    actualPrice: 8.99,
    discountPrice: 7.49,
    discountPercentage: 16.69,
  },
  {
    productImage: 'image12.jpg',
    productTitle: 'Orthopedic Pillow',
    actualPrice: 24.99,
    discountPrice: 21.49,
    discountPercentage: 14.00,
  },
  {
    productImage: 'image13.jpg',
    productTitle: 'Blood Pressure Monitor',
    actualPrice: 34.99,
    discountPrice: 29.99,
    discountPercentage: 14.29,
  },
  {
    productImage: 'image14.jpg',
    productTitle: 'Dental Floss',
    actualPrice: 3.99,
    discountPrice: 2.99,
    discountPercentage: 25.06,
  },
  {
    productImage: 'image15.jpg',
    productTitle: 'Sleep Aid Tablets',
    actualPrice: 18.99,
    discountPrice: 16.49,
    discountPercentage: 13.18,
  },
  {
    productImage: 'image16.jpg',
    productTitle: 'Insect Repellent Spray',
    actualPrice: 9.99,
    discountPrice: 8.49,
    discountPercentage: 15.02,
  },
  {
    productImage: 'image17.jpg',
    productTitle: 'Multivitamin Gummies',
    actualPrice: 14.99,
    discountPrice: 11.99,
    discountPercentage: 20.01,
  },
  {
    productImage: 'image18.jpg',
    productTitle: 'Wound Cleanser Solution',
    actualPrice: 12.49,
    discountPrice: 9.99,
    discountPercentage: 20.02,
  },
  {
    productImage: 'image19.jpg',
    productTitle: 'Sunscreen Lotion',
    actualPrice: 16.99,
    discountPrice: 14.49,
    discountPercentage: 14.72,
  },
  {
    productImage: 'image20.jpg',
    productTitle: 'Digital Blood Glucose Monitor',
    actualPrice: 39.99,
    discountPrice: 34.99,
    discountPercentage: 12.50,
  },
  {
    productImage: 'image21.jpg',
    productTitle: 'Anti-Fungal Cream',
    actualPrice: 7.49,
    discountPrice: 5.99,
    discountPercentage: 20.03,
  },
  {
    productImage: 'image22.jpg',
    productTitle: 'Joint Pain Relief Cream',
    actualPrice: 15.99,
    discountPrice: 12.99,
    discountPercentage: 18.76,
  },
  {
    productImage: 'image23.jpg',
    productTitle: 'Digestive Enzyme Supplements',
    actualPrice: 22.99,
    discountPrice: 19.99,
    discountPercentage: 13.05,
  },
  {
    productImage: 'image24.jpg',
    productTitle: 'Disposable Face Masks (Pack of 50)',
    actualPrice: 19.99,
    discountPrice: 14.99,
    discountPercentage: 25.01,
  },
  {
    productImage: 'image25.jpg',
    productTitle: 'Hair Loss Treatment Shampoo',
    actualPrice: 13.99,
    discountPrice: 11.99,
    discountPercentage: 14.29,
  },
];


export const babyProducts = [
  {
    productImage: 'baby_image1.jpg',
    productTitle: 'Baby Diapers (Pack of 50)',
    actualPrice: 24.99,
    discountPrice: 19.99,
    discountPercentage: 20,
  },
  {
    productImage: 'baby_image2.jpg',
    productTitle: 'Baby Wipes (Sensitive Skin)',
    actualPrice: 9.99,
    discountPrice: 7.49,
    discountPercentage: 25,
  },
  {
    productImage: 'baby_image3.jpg',
    productTitle: 'Infant Formula (Stage 1)',
    actualPrice: 29.99,
    discountPrice: 24.99,
    discountPercentage: 16.67,
  },
  {
    productImage: 'baby_image4.jpg',
    productTitle: 'Baby Onesies (Set of 3)',
    actualPrice: 14.99,
    discountPrice: 11.99,
    discountPercentage: 20.01,
  },
  {
    productImage: 'baby_image5.jpg',
    productTitle: 'Baby Shampoo and Wash',
    actualPrice: 8.99,
    discountPrice: 6.99,
    discountPercentage: 22.25,
  },
  {
    productImage: 'baby_image6.jpg',
    productTitle: 'Convertible Baby Car Seat',
    actualPrice: 89.99,
    discountPrice: 74.99,
    discountPercentage: 16.67,
  },
  {
    productImage: 'baby_image7.jpg',
    productTitle: 'Baby Blanket (Soft and Cozy)',
    actualPrice: 12.99,
    discountPrice: 10.99,
    discountPercentage: 15.39,
  },
  {
    productImage: 'baby_image8.jpg',
    productTitle: 'Baby Food Pouches (Pack of 10)',
    actualPrice: 16.99,
    discountPrice: 13.99,
    discountPercentage: 17.66,
  },
  {
    productImage: 'baby_image9.jpg',
    productTitle: 'Baby Monitor with Camera',
    actualPrice: 49.99,
    discountPrice: 39.99,
    discountPercentage: 20,
  },
  {
    productImage: 'baby_image10.jpg',
    productTitle: 'Toddler Training Potty',
    actualPrice: 19.99,
    discountPrice: 16.49,
    discountPercentage: 17.51,
  },
  {
    productImage: 'baby_image11.jpg',
    productTitle: 'Baby Teething Toys (Set of 3)',
    actualPrice: 8.49,
    discountPrice: 6.99,
    discountPercentage: 17.65,
  },
  {
    productImage: 'baby_image12.jpg',
    productTitle: 'Baby Stroller with Sunshade',
    actualPrice: 59.99,
    discountPrice: 49.99,
    discountPercentage: 16.67,
  },
  {
    productImage: 'baby_image13.jpg',
    productTitle: 'Baby Bath Tub (Foldable)',
    actualPrice: 19.99,
    discountPrice: 16.99,
    discountPercentage: 15.01,
  },
  {
    productImage: 'baby_image14.jpg',
    productTitle: 'Baby Sippy Cups (Pack of 2)',
    actualPrice: 6.99,
    discountPrice: 5.49,
    discountPercentage: 21.44,
  },
  {
    productImage: 'baby_image15.jpg',
    productTitle: 'Diaper Bag Backpack',
    actualPrice: 29.99,
    discountPrice: 24.99,
    discountPercentage: 16.67,
  },
  {
    productImage: 'baby_image16.jpg',
    productTitle: 'Baby High Chair',
    actualPrice: 39.99,
    discountPrice: 34.99,
    discountPercentage: 12.5,
  },
  {
    productImage: 'baby_image17.jpg',
    productTitle: 'Baby Swaddle Blankets (Set of 4)',
    actualPrice: 16.99,
    discountPrice: 14.49,
    discountPercentage: 14.72,
  },
  {
    productImage: 'baby_image18.jpg',
    productTitle: 'Baby Play Mat (Non-Toxic)',
    actualPrice: 22.99,
    discountPrice: 19.99,
    discountPercentage: 13.05,
  },
  {
    productImage: 'baby_image19.jpg',
    productTitle: 'Baby Nose Aspirator',
    actualPrice: 8.49,
    discountPrice: 6.99,
    discountPercentage: 17.65,
  },
  {
    productImage: 'baby_image20.jpg',
    productTitle: 'Baby Changing Pad',
    actualPrice: 12.49,
    discountPrice: 9.99,
    discountPercentage: 20.02,
  },
  {
    productImage: 'baby_image21.jpg',
    productTitle: 'Baby Sun Hat (UPF 50+)',
    actualPrice: 11.99,
    discountPrice: 9.99,
    discountPercentage: 16.68,
  },
  {
    productImage: 'baby_image22.jpg',
    productTitle: 'Baby Nail Clippers Set',
    actualPrice: 5.99,
    discountPrice: 4.49,
    discountPercentage: 25.04,
  },
  {
    productImage: 'baby_image23.jpg',
    productTitle: 'Baby Hooded Towels (Set of 3)',
    actualPrice: 18.99,
    discountPrice: 16.49,
    discountPercentage: 13.18,
  },
  {
    productImage: 'baby_image24.jpg',
    productTitle: 'Baby Crib Mobile',
    actualPrice: 14.99,
    discountPrice: 11.99,
    discountPercentage: 20.01,
  },
  {
    productImage: 'baby_image25.jpg',
    productTitle: 'Baby Safety Gate',
    actualPrice: 29.99,
    discountPrice: 24.99,
    discountPercentage: 16.67,
  },
];


export const medicineBrands = [
  {brandImg: 'medixcare.jpg', brandName: 'MedixCare'},
  {brandImg: 'pharmavista.jpg', brandName: 'PharmaVista'},
  {brandImg: 'curewell.jpg', brandName: 'CureWell'},
  {brandImg: 'healthguard.jpg', brandName: 'HealthGuard'},
  {brandImg: 'medsolutions.jpg', brandName: 'MedSolutions'},
  {brandImg: 'vitacure.jpg', brandName: 'VitaCure'},
  {brandImg: 'meditrust.jpg', brandName: 'MediTrust'},
  {brandImg: 'healrx.jpg', brandName: 'HealRx'},
  {brandImg: 'biopharm.jpg', brandName: 'BioPharm'},
  {brandImg: 'medlifeplus.jpg', brandName: 'MedLife Plus'},
  {brandImg: 'purecure.jpg', brandName: 'PureCure'},
  {brandImg: 'medblend.jpg', brandName: 'MedBlend'},
  {brandImg: 'wellpharma.jpg', brandName: 'WellPharma'},
  {brandImg: 'curelink.jpg', brandName: 'CureLink'},
  {brandImg: 'medessence.jpg', brandName: 'MedEssence'},
];


export const healthConditions = [
  {icon: <FaHeart />, healthCondition: 'Heart Health'},
  {icon: <FaBloodSugar />, healthCondition: 'Diabetes Care'},
  {icon: <FaBrain />, healthCondition: 'Mental Wellness'},
  {icon: <FaBone />, healthCondition: 'Bone and Joint Health'},
  {icon: <FaStethoscope />, healthCondition: 'Digestive Health'},
  {icon: <FaLungs />, healthCondition: 'Respiratory Health'},
  {icon: <FaVenus />, healthCondition: "Women's Health"},
  {icon: <FaMars />, healthCondition: "Men's Health"},
  {icon: <FaAllergies />, healthCondition: 'Allergy Management'},
  {icon: <FaRegSmile />, healthCondition: 'Skin Care'},
];

export const valueDeals = [
  {
    productImage: 'deal_image1.jpg',
    productTitle: 'Pain Relief Bundle',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image2.jpg',
    productTitle: 'Cold and Flu Essentials Pack',
    actualPrice: 100,
    discountPrice: 80,
    discountPercentage: 20,
  },
  {
    productImage: 'deal_image3.jpg',
    productTitle: 'Vitamin Boost Combo',
    actualPrice: 100,
    discountPrice: 70,
    discountPercentage: 30,
  },
  {
    productImage: 'deal_image4.jpg',
    productTitle: 'First Aid Kit Set',
    actualPrice: 100,
    discountPrice: 85,
    discountPercentage: 15,
  },
  {
    productImage: 'deal_image5.jpg',
    productTitle: 'Health Supplements Pack',
    actualPrice: 100,
    discountPrice: 60,
    discountPercentage: 40,
  },
  {
    productImage: 'deal_image6.jpg',
    productTitle: 'Allergy Relief Bundle',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image7.jpg',
    productTitle: 'Digital Health Devices Combo',
    actualPrice: 100,
    discountPrice: 90,
    discountPercentage: 10,
  },
  {
    productImage: 'deal_image8.jpg',
    productTitle: 'Eye Care Essentials Kit',
    actualPrice: 100,
    discountPrice: 80,
    discountPercentage: 20,
  },
  {
    productImage: 'deal_image9.jpg',
    productTitle: 'Digestive Health Pack',
    actualPrice: 100,
    discountPrice: 70,
    discountPercentage: 30,
  },
  {
    productImage: 'deal_image10.jpg',
    productTitle: 'Wellness Starter Pack',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image11.jpg',
    productTitle: 'Sleep Aid Combo',
    actualPrice: 100,
    discountPrice: 85,
    discountPercentage: 15,
  },
  {
    productImage: 'deal_image12.jpg',
    productTitle: 'Blood Pressure Monitor Set',
    actualPrice: 100,
    discountPrice: 80,
    discountPercentage: 20,
  },
  {
    productImage: 'deal_image13.jpg',
    productTitle: 'Dental Care Bundle',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image14.jpg',
    productTitle: 'Joint Health Pack',
    actualPrice: 100,
    discountPrice: 90,
    discountPercentage: 10,
  },
  {
    productImage: 'deal_image15.jpg',
    productTitle: 'Immunity Boosters Combo',
    actualPrice: 100,
    discountPrice: 70,
    discountPercentage: 30,
  },
  {
    productImage: 'deal_image16.jpg',
    productTitle: 'Anti-Stress Kit',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image17.jpg',
    productTitle: 'Weight Management Bundle',
    actualPrice: 100,
    discountPrice: 80,
    discountPercentage: 20,
  },
  {
    productImage: 'deal_image18.jpg',
    productTitle: 'Hair Care Essentials Pack',
    actualPrice: 100,
    discountPrice: 70,
    discountPercentage: 30,
  },
  {
    productImage: 'deal_image19.jpg',
    productTitle: 'Travel Health Kit',
    actualPrice: 100,
    discountPrice: 85,
    discountPercentage: 15,
  },
  {
    productImage: 'deal_image20.jpg',
    productTitle: 'Baby Health Essentials Set',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image21.jpg',
    productTitle: 'Senior Wellness Package',
    actualPrice: 100,
    discountPrice: 90,
    discountPercentage: 10,
  },
  {
    productImage: 'deal_image22.jpg',
    productTitle: 'Covid Care Kit',
    actualPrice: 100,
    discountPrice: 80,
    discountPercentage: 20,
  },
  {
    productImage: 'deal_image23.jpg',
    productTitle: 'Pet Health Combo',
    actualPrice: 100,
    discountPrice: 70,
    discountPercentage: 30,
  },
  {
    productImage: 'deal_image24.jpg',
    productTitle: 'Sports Nutrition Pack',
    actualPrice: 100,
    discountPrice: 75,
    discountPercentage: 25,
  },
  {
    productImage: 'deal_image25.jpg',
    productTitle: 'Family Health Bundle',
    actualPrice: 100,
    discountPrice: 90,
    discountPercentage: 10,
  },
];

export const frequentlyAskedQuestions = [
  {
    question: 'How can I place an order?',
    answer: 'You can easily place an order on our website by browsing the products, adding them to your cart, and proceeding to checkout. Follow the simple steps to complete your purchase.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept various payment methods, including credit/debit cards, online wallets, and other secure payment options. Choose the method that suits you best during the checkout process.',
  },
  {
    question: 'Can I modify or cancel my order?',
    answer: 'Once an order is placed, modifications or cancellations may not be possible. Please review your order carefully before confirming the purchase. If you encounter any issues, contact our customer support.',
  },
  {
    question: 'How can I track my order?',
    answer: 'Once your order is dispatched, you will receive a tracking number via email. You can use this tracking number to monitor the status and location of your package.',
  },
  {
    question: 'What is your return policy?',
    answer: 'We have a hassle-free return policy. If you are not satisfied with your purchase, you can initiate a return within a specified period. Please refer to our Return Policy for more details.',
  },
  {
    question: 'How do I contact customer support?',
    answer: 'If you have any questions, concerns, or issues, you can contact our customer support team through the contact form on our website or by reaching out to our customer service hotline.',
  },
];
